# -*- coding: utf-8 -*-
"""Course Registration and Advisor System.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QmDkPtRCTC3uHTryxW0coqbGX6HtYRTo
"""

# ================= SMART COURSE REGISTRATION & ADVISING SYSTEM =================
# Run this entire code in ONE Google Colab cell

# ================= INSTALL PYTHON PACKAGES =================
print("📦 Installing required packages...")
!pip install gradio -q

print("✅ Packages installed successfully!")
print("⏳ Starting application...\n")

# ================= IMPORTS =================
import gradio as gr
import sqlite3

# ================= DATABASE SETUP =================
def setup_database():
    conn = sqlite3.connect("course_system.db", check_same_thread=False)
    cursor = conn.cursor()

    # USERS
    cursor.execute("""
    CREATE TABLE IF NOT EXISTS users (
        username TEXT PRIMARY KEY,
        password TEXT,
        role TEXT
    )
    """)

    # COURSES
    cursor.execute("""
    CREATE TABLE IF NOT EXISTS courses (
        course_code TEXT PRIMARY KEY,
        course_title TEXT,
        prerequisite TEXT
    )
    """)

    # REGISTRATIONS
    cursor.execute("""
    CREATE TABLE IF NOT EXISTS registrations (
        student TEXT,
        course_code TEXT,
        status TEXT
    )
    """)

    conn.commit()
    return conn, cursor

conn, cursor = setup_database()

# ================= GLOBAL USER =================
current_user = {"username": None, "role": None}

# ================= REGISTER =================
def register_user(username, password, role):
    if not username or not password:
        return "❌ All fields are required"

    try:
        cursor.execute(
            "INSERT INTO users VALUES (?, ?, ?)",
            (username, password, role)
        )
        conn.commit()
        return f"✅ Registered successfully as {role}"
    except sqlite3.IntegrityError:
        return "❌ Username already exists"

# ================= LOGIN =================
def login_user(username, password):
    cursor.execute(
        "SELECT role FROM users WHERE username=? AND password=?",
        (username, password)
    )
    result = cursor.fetchone()

    if result:
        current_user["username"] = username
        current_user["role"] = result[0]
        return f"✅ Logged in as {result[0]}"
    return "❌ Invalid login details"

# ================= ADD COURSE (ADVISOR) =================
def add_course(code, title, prerequisite):
    if current_user["role"] != "Advisor":
        return "❌ Only advisors can add courses"

    try:
        cursor.execute(
            "INSERT INTO courses VALUES (?, ?, ?)",
            (code, title, prerequisite)
        )
        conn.commit()
        return f"✅ Course {code} added successfully"
    except sqlite3.IntegrityError:
        return "❌ Course already exists"

# ================= VIEW COURSES =================
def view_courses():
    cursor.execute("SELECT * FROM courses")
    courses = cursor.fetchall()

    if not courses:
        return "📋 No courses available"

    text = "📘 Available Courses\n\n"
    text += "| Code | Title | Prerequisite |\n"
    text += "|------|-------|--------------|\n"

    for c in courses:
        text += f"| {c[0]} | {c[1]} | {c[2] or 'None'} |\n"

    return text

# ================= REGISTER COURSE (STUDENT) =================
def register_course(course_code):
    if current_user["role"] != "Student":
        return "❌ Only students can register courses"

    cursor.execute(
        "SELECT prerequisite FROM courses WHERE course_code=?",
        (course_code,)
    )
    course = cursor.fetchone()

    if not course:
        return "❌ Course does not exist"

    prerequisite = course[0]

    if prerequisite:
        cursor.execute(
            "SELECT * FROM registrations WHERE student=? AND course_code=? AND status='Approved'",
            (current_user["username"], prerequisite)
        )
        if not cursor.fetchone():
            return f"❌ Prerequisite {prerequisite} not satisfied"

    cursor.execute(
        "INSERT INTO registrations VALUES (?, ?, ?)",
        (current_user["username"], course_code, "Pending")
    )
    conn.commit()

    return "✅ Course registration submitted (Pending approval)"

# ================= VIEW PENDING REQUESTS (ADVISOR) =================
def view_requests():
    if current_user["role"] != "Advisor":
        return "❌ Only advisors can view requests"

    cursor.execute(
        "SELECT * FROM registrations WHERE status='Pending'"
    )
    records = cursor.fetchall()

    if not records:
        return "📋 No pending requests"

    text = "📋 Pending Course Requests\n\n"
    text += "| Student | Course | Status |\n"
    text += "|---------|--------|--------|\n"

    for r in records:
        text += f"| {r[0]} | {r[1]} | {r[2]} |\n"

    return text

# ================= APPROVE COURSE =================
def approve_course(student, course):
    if current_user["role"] != "Advisor":
        return "❌ Only advisors can approve"

    cursor.execute(
        "UPDATE registrations SET status='Approved' WHERE student=? AND course_code=?",
        (student, course)
    )
    conn.commit()
    return "✅ Course approved successfully"

# ================= VIEW MY COURSES =================
def view_my_courses():
    if current_user["role"] != "Student":
        return "❌ Only students can view this"

    cursor.execute(
        "SELECT course_code, status FROM registrations WHERE student=?",
        (current_user["username"],)
    )
    records = cursor.fetchall()

    if not records:
        return "📋 No registered courses"

    text = "📘 My Courses\n\n"
    text += "| Course | Status |\n"
    text += "|--------|--------|\n"

    for r in records:
        text += f"| {r[0]} | {r[1]} |\n"

    return text

# ================= LOGOUT =================
def logout():
    current_user["username"] = None
    current_user["role"] = None
    return "✅ Logged out"

# ================= USER STATUS =================
def user_status():
    if current_user["username"]:
        return f"👤 {current_user['username']} ({current_user['role']})"
    return "👤 Not logged in"

# ================= GRADIO UI =================
with gr.Blocks(theme=gr.themes.Soft(), title="Smart Course Registration System") as app:

    gr.Markdown("# 🎓 Smart Course Registration & Advising System")
    status = gr.Markdown(user_status())

    with gr.Tabs():

        with gr.Tab("📝 Register"):
            u = gr.Textbox(label="Username")
            p = gr.Textbox(label="Password", type="password")
            r = gr.Radio(["Student", "Advisor"], label="Role")
            o = gr.Textbox(label="Status")
            gr.Button("Register").click(register_user, [u, p, r], o)

        with gr.Tab("🔐 Login"):
            u = gr.Textbox(label="Username")
            p = gr.Textbox(label="Password", type="password")
            o = gr.Textbox(label="Status")
            gr.Button("Login").click(
                lambda x, y: (login_user(x, y), user_status()),
                [u, p],
                [o, status]
            )

        with gr.Tab("👨‍🏫 Advisor Dashboard"):
            c1 = gr.Textbox(label="Course Code")
            c2 = gr.Textbox(label="Course Title")
            c3 = gr.Textbox(label="Prerequisite (optional)")
            out = gr.Textbox(label="Status")
            gr.Button("Add Course").click(add_course, [c1, c2, c3], out)

            gr.Markdown("### Pending Requests")
            gr.Button("View Requests").click(view_requests, None, out)

            s = gr.Textbox(label="Student Username")
            c = gr.Textbox(label="Course Code")
            gr.Button("Approve Course").click(approve_course, [s, c], out)

        with gr.Tab("👨‍🎓 Student Dashboard"):
            gr.Button("View Courses").click(view_courses, None, gr.Textbox())
            course = gr.Textbox(label="Course Code")
            gr.Button("Register Course").click(register_course, course, gr.Textbox())
            gr.Button("My Courses").click(view_my_courses, None, gr.Textbox())

        with gr.Tab("🚪 Logout"):
            gr.Button("Logout").click(
                lambda: (logout(), user_status()),
                None,
                [gr.Textbox(), status]
            )

app.launch(share=True)

print("ended")

